/* ═══════════════════════════════════════════════════════════════════════
   cards-data.js — AUTO-GENERATED by scripts/generate-content.mjs. Do not
   edit by hand: run `npm run content:generate` after editing the content
   sources in content/cases/*.json (order: content/settings.json cardOrder).

   window.CARDS_DATA — финальная развёрнутая структура кейсов (бывший
   makeItems() из js/main.js портирован в генератор):
     items.media[5] — 2 wide + 3 tall, src по умолчанию
       ./assets/cases/<id>/01..05.svg (переопределяется case.srcs[i]);
     items.text / items.inline — текстовые блоки (или null);
     items.motionBlocks — fixed motion-секции (или null).
   Подключается ПЕРЕД js/main.js (classic script, без defer/async).
═══════════════════════════════════════════════════════════════════════ */
window.CARDS_DATA = {
  'orbital-mk-ii': {
    role: 'Personal',
    tools: [
      'Blender',
      'Substance Painter',
      'Marmoset'
    ],
    modelSrc: './assets/models/experimental/dino.glb',
    modelEnvironment: 'studio',
    modelExposure: 1.05,
    modelStats: {
      triangles: 'Draco compressed',
      vertices: 'GLB embedded',
      materials: 1,
      textures: '3 embedded',
      software: 'Drive test asset'
    },
    items: {
      media: [
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/orbital-mk-ii/01.svg',
          bg: 'linear-gradient(135deg,#1e2d3d 0%,#2a3a4a 100%)',
          label: 'Hero render',
          desc: 'Sci-fi prop engineered for AAA pipeline. Full PBR, clean manifold topology.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/orbital-mk-ii/02.png',
          bg: 'linear-gradient(135deg,#1a2535 0%,#22303f 100%)',
          label: 'Material study',
          desc: 'Secondary shell finish under studio HDRI, checked for silhouette readability.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/orbital-mk-ii/03.svg',
          bg: 'linear-gradient(135deg,#152030 0%,#1e2c3c 100%)',
          label: 'Topology pass',
          desc: '18 k clean quads. Subdivision-ready and LOD0-certified for real-time integration.',
          enabled: true
        },
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/orbital-mk-ii/04.svg',
          bg: 'linear-gradient(135deg,#112030 0%,#1a2c3c 100%)',
          label: 'Detail close-up',
          desc: 'Panel seam macro. Bevel widths tuned for 2 m viewing distance at 4 K resolution.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/orbital-mk-ii/05.svg',
          bg: 'linear-gradient(135deg,#0e1a28 0%,#182636 100%)',
          label: 'Final composite',
          desc: 'Lit with 3-point studio HDRI. Denoised in OptiX, tonemapped ACES.',
          enabled: true
        }
      ],
      text: {
        title: 'Pipeline fit',
        body: 'Delivered as a game-ready asset with LOD0–LOD2 and a separate cinematic mesh for marketing renders. Naming and pivot conventions follow Unreal Engine 5 standards.'
      },
      inline: {
        title: 'Texture budget',
        body: 'Single 4 K texture set for hero, separate 2 K sets per LOD stage. Roughness authored in 16-bit to preserve micro-detail.'
      },
      motionBlocks: [
        {
          source: 'local',
          layout: 'wide',
          playback: 'ambient',
          src: './assets/cases/orbital-mk-ii/orbital-shell-idle.webm',
          poster: './assets/cases/orbital-mk-ii/01.svg',
          label: 'Seamless shell loop',
          desc: 'A silent in-case motion plate for the orbital shell idle cycle. Built to accept final local media without renderer changes.'
        },
        {
          source: 'vimeo',
          layout: 'wide',
          playback: 'controlled',
          vimeoId: '76979871',
          poster: './assets/cases/orbital-mk-ii/04.svg',
          title: 'Orbital Mk.II assembly loop',
          label: 'Assembly motion study',
          desc: 'A Vimeo-backed motion slot for client review cuts, with the same case-native play and pause control as local media.'
        },
        {
          source: 'local',
          layout: 'half',
          playback: 'controlled',
          src: './assets/cases/orbital-mk-ii/orbital-detail-loop.webm',
          poster: './assets/cases/orbital-mk-ii/02.png',
          label: 'Detail loop control',
          desc: 'A compact local motion block for panel and material passes. The control state is owned by the case UI, not native browser chrome.'
        },
        {
          source: 'vimeo',
          layout: 'half',
          playback: 'ambient',
          vimeoId: '76979871',
          poster: './assets/cases/orbital-mk-ii/05.svg',
          title: 'Orbital Mk.II ambient loop',
          label: 'Ambient service loop',
          desc: 'A silent Vimeo loop slot for externally hosted animation previews, lazy-loaded only when the motion block is approached.'
        }
      ]
    }
  },
  'vega-shell': {
    role: 'Personal',
    tools: [
      'Blender',
      'ZBrush',
      'Substance Painter'
    ],
    modelSrc: './assets/models/experimental/humanoid-2.glb',
    modelEnvironment: 'studio',
    modelExposure: 1.05,
    modelStats: {
      triangles: 'Meshopt compressed',
      vertices: 'GLB embedded',
      materials: 1,
      textures: '2 KTX2',
      software: 'Drive test asset'
    },
    items: {
      media: [
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/vega-shell/01.svg',
          bg: 'linear-gradient(135deg,#1a2030 0%,#252e40 100%)',
          label: 'System overview',
          desc: 'Modular exo-armor built from 47 individual pieces. Each segment detaches for LOD and rigging.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/vega-shell/02.svg',
          bg: 'linear-gradient(135deg,#161c2e 0%,#20283c 100%)',
          label: 'Component breakdown',
          desc: 'Parting logic derived from real manufacturing constraints. No floating geo, clean hard-edges.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/vega-shell/03.svg',
          bg: 'linear-gradient(135deg,#111828 0%,#1a2234 100%)',
          label: 'LOD passes',
          desc: 'LOD0–LOD2 prepared at 100 %, 40 % and 12 % poly budgets for runtime mesh streaming.',
          enabled: true
        },
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/vega-shell/04.svg',
          bg: 'linear-gradient(135deg,#0d1422 0%,#161e2e 100%)',
          label: 'Shoulder plate',
          desc: 'Ball-joint attachment with limit constraints baked into naming. Ready for IK retarget.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/vega-shell/05.svg',
          bg: 'linear-gradient(135deg,#0b1220 0%,#141c2a 100%)',
          label: 'Paint variant',
          desc: 'Three material presets — factory clean, field-worn, arctic camo — via ID-mask layering.',
          enabled: true
        }
      ],
      text: {
        title: 'Why modularity',
        body: 'Each of the 47 parts can be hot-swapped at runtime to support player customisation. Every seam has been modelled as a mechanical connection rather than a floating surface decal.'
      },
      inline: {
        title: 'Rigging ready',
        body: 'Each segment carries a hidden socket bone. Joint orientation follows FBX conventions for seamless Maya/Blender export.'
      },
      motionBlocks: null
    }
  },
  'ironclad-frame': {
    role: 'R&D',
    tools: [
      'Blender',
      'CAD import',
      'Inkscape'
    ],
    modelSrc: './assets/models/experimental/car-paint.glb',
    modelEnvironment: 'studio',
    modelExposure: 1.05,
    modelStats: {
      triangles: 'Draco compressed',
      vertices: 'GLB embedded',
      materials: 1,
      textures: '3 embedded',
      software: 'Drive test asset'
    },
    items: {
      media: [
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/ironclad-frame/01.svg',
          bg: 'linear-gradient(135deg,#1c2428 0%,#28343a 100%)',
          label: 'Full assembly',
          desc: 'Industrial chassis breakdown. Every bolt and seam modeled to engineering specification.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/ironclad-frame/02.svg',
          bg: 'linear-gradient(135deg,#181e22 0%,#222e34 100%)',
          label: 'Part isolation',
          desc: 'Selected sub-assembly with material IDs highlighted. 24 individually named mesh objects.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/ironclad-frame/03.svg',
          bg: 'linear-gradient(135deg,#141a1e 0%,#1c2830 100%)',
          label: 'Production notes',
          desc: 'Annotated render set delivered to engineering team as vector-accurate reference PDF.',
          enabled: true
        },
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/ironclad-frame/04.svg',
          bg: 'linear-gradient(135deg,#10161a 0%,#18242c 100%)',
          label: 'Load diagram',
          desc: 'Stress-path overlay generated in Blender Compositing from engineering FEA export.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/ironclad-frame/05.svg',
          bg: 'linear-gradient(135deg,#0c1216 0%,#141e26 100%)',
          label: 'Finish variants',
          desc: 'Powder-coat and raw-steel renders delivered for catalogue and technical documentation.',
          enabled: true
        }
      ],
      text: {
        title: 'Reference accuracy',
        body: 'Modelled directly from issued engineering CAD — every hole pattern, bolt head and weld bead matches the real part to within 0.5 mm at full scale.'
      },
      inline: {
        title: 'Weight target',
        body: 'Under 28 k tris at LOD0. Silhouette readable at 512 px. First-person camera tested at 2 m and 6 m focal distance.'
      },
      motionBlocks: null
    }
  },
  'corten-series': {
    role: 'Client',
    tools: [
      'Blender',
      'Substance Painter',
      'DaVinci Resolve'
    ],
    modelSrc: './assets/models/corten-series.glb',
    modelStats: {
      triangles: '60',
      vertices: '40',
      materials: 1,
      textures: 'Procedural (PBR)',
      software: 'Blender'
    },
    items: {
      media: [
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/corten-series/01.svg',
          bg: 'linear-gradient(135deg,#2a2018 0%,#3a2e22 100%)',
          label: 'Studio render',
          desc: 'Product viz for an industrial furniture brand. Corten steel material, HDR studio lighting.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/corten-series/02.svg',
          bg: 'linear-gradient(135deg,#241a14 0%,#34281e 100%)',
          label: 'Context shot',
          desc: 'In-situ placement render in a concrete loft environment. Used as lead image for the launch deck.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/corten-series/03.svg',
          bg: 'linear-gradient(135deg,#1e1410 0%,#2c2018 100%)',
          label: 'Material passes',
          desc: 'Raw metal base, rust gradient pass, and clearcoat variation delivered for print and web.',
          enabled: true
        },
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/corten-series/04.svg',
          bg: 'linear-gradient(135deg,#180e0a 0%,#281c12 100%)',
          label: 'Detail macro',
          desc: 'Texture close-up showing procedural oxidation, patina and surface imperfection layers.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/corten-series/05.svg',
          bg: 'linear-gradient(135deg,#120a08 0%,#20150e 100%)',
          label: 'Lineup shot',
          desc: 'Full collection rendered as a lineup for the catalogue spread. Lighting matches brand art direction.',
          enabled: true
        }
      ],
      text: {
        title: 'Material approach',
        body: 'The Corten oxidation is procedural, not painted. A single material graph drives rust density, micro-pitting and runoff stains — each chair variant reads as a unique piece without repeating textures.'
      },
      inline: {
        title: 'Patina system',
        body: 'Rust generated from curvature + ambient occlusion masks. Two layers: oxide underneath, flake breakup on top, roughness offset per layer.'
      },
      motionBlocks: null
    }
  },
  'lumen-one': {
    role: 'Client',
    tools: [
      'Blender',
      'Inkscape'
    ],
    modelSrc: './assets/models/lumen-one.glb',
    modelStats: {
      triangles: '1,352',
      vertices: '690',
      materials: 1,
      textures: '1 × 2 K',
      software: 'Blender + Substance'
    },
    items: {
      media: [
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/lumen-one/01.svg',
          bg: 'linear-gradient(135deg,#1e2428 0%,#2c3640 100%)',
          label: 'Final render',
          desc: 'Architectural lighting unit. Photorealistic turntable deliverable for investor pitch deck.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/lumen-one/02.svg',
          bg: 'linear-gradient(135deg,#1a2024 0%,#28303c 100%)',
          label: 'Lighting setup',
          desc: '3-point HDRI rig with area light fill. Caustics rendered via path-tracing at 4096 samples.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/lumen-one/03.svg',
          bg: 'linear-gradient(135deg,#161c20 0%,#222c38 100%)',
          label: 'Spec sheet',
          desc: 'Dimension overlay and material callout sheet generated in Blender Compositing and Inkscape.',
          enabled: true
        },
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/lumen-one/04.svg',
          bg: 'linear-gradient(135deg,#11181c 0%,#1c2832 100%)',
          label: 'Context shot',
          desc: 'Hero placement in a modern office environment, shot from client-approved camera angle.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/lumen-one/05.svg',
          bg: 'linear-gradient(135deg,#0c1418 0%,#18242e 100%)',
          label: 'Colour variants',
          desc: 'Six finish variants — brass, chrome, matte black, warm white — rendered as catalogue sprites.',
          enabled: true
        }
      ],
      text: {
        title: 'Light behaviour',
        body: 'The optical housing uses a real IES profile exported from the client’s photometric test. Caustics and beam spread on camera match what the product produces on a physical wall.'
      },
      inline: {
        title: 'Light model',
        body: 'Filament IES bakes drive the emissive intensity map. Inner diffuser scatters via subsurface approximation — no cheat geometry.'
      },
      motionBlocks: null
    }
  },
  'flux-capsule': {
    role: 'R&D',
    tools: [
      'Blender',
      'Substance Painter'
    ],
    modelSrc: './assets/models/flux-capsule.glb',
    modelStats: {
      triangles: '608',
      vertices: '312',
      materials: 3,
      textures: 'Procedural (PBR)',
      software: 'Blender'
    },
    items: {
      media: [
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/flux-capsule/01.svg',
          bg: 'linear-gradient(135deg,#1e2030 0%,#282a40 100%)',
          label: 'Product shot',
          desc: 'Consumer tech device. E-commerce hero shot with studio HDRI and custom denoising.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/flux-capsule/02.svg',
          bg: 'linear-gradient(135deg,#1a1c2c 0%,#24263c 100%)',
          label: '360° view',
          desc: 'Full turntable sequence — 36 frames at 10° increments. Exported as WebP sprite strip.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/flux-capsule/03.svg',
          bg: 'linear-gradient(135deg,#161828 0%,#202234 100%)',
          label: 'Detail macro',
          desc: 'Micro-surface texture pass. Sub-millimetre detail captured with a virtual macro lens rig.',
          enabled: true
        },
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/flux-capsule/04.svg',
          bg: 'linear-gradient(135deg,#12142a 0%,#1c1e30 100%)',
          label: 'Packaging',
          desc: 'Retail box render with reflective foil stamping, printed using PBR metallic-clearcoat.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/flux-capsule/05.svg',
          bg: 'linear-gradient(135deg,#0e102a 0%,#181a2a 100%)',
          label: 'Scale ref',
          desc: 'Hand comparison render to communicate size without breaking photo-neutral background.',
          enabled: true
        }
      ],
      text: {
        title: 'Launch ready',
        body: 'All hero assets were delivered as 6 K master renders plus derivative crops for Shopify, Amazon and paid-social ad placements. Colour profile matches the brand Pantone book.'
      },
      inline: {
        title: 'Containment',
        body: 'Animated shader on the core reads a custom gradient texture — no vertex morph, no simulation cache. Runs at 240 FPS on mid-range GPUs.'
      },
      motionBlocks: null
    }
  },
  nightshard: {
    role: 'Personal',
    tools: [
      'Blender',
      'Substance Painter',
      'UE5'
    ],
    modelSrc: './assets/models/nightshard.glb',
    modelStats: {
      triangles: '15,488',
      vertices: '8,000',
      materials: 1,
      textures: '5 × 4 K',
      software: 'Blender + Substance'
    },
    items: {
      media: [
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/nightshard/01.svg',
          bg: 'linear-gradient(135deg,#1a1a2a 0%,#252535 100%)',
          label: 'Final asset',
          desc: 'Hero weapon for a third-person action title. 4K PBR textures, optimised for real-time.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/nightshard/02.svg',
          bg: 'linear-gradient(135deg,#161624 0%,#202030 100%)',
          label: 'Texture sheets',
          desc: 'Albedo, roughness, metalness, normal and AO maps. Baked from 8M-poly high source.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/nightshard/03.svg',
          bg: 'linear-gradient(135deg,#121220 0%,#1c1c2c 100%)',
          label: 'Polycount view',
          desc: 'Game-ready mesh at 12 k triangles — within budget for character-attachment LOD0.',
          enabled: true
        },
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/nightshard/04.svg',
          bg: 'linear-gradient(135deg,#0e0e1c 0%,#181828 100%)',
          label: 'In-engine test',
          desc: 'Live capture inside Unreal Engine 5 using Nanite-disabled preview with Lumen.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/nightshard/05.svg',
          bg: 'linear-gradient(135deg,#0a0a18 0%,#161626 100%)',
          label: 'Blade macro',
          desc: 'Edge chip detail pass. Anisotropic reflection matches reference from real forged steel.',
          enabled: true
        }
      ],
      text: {
        title: 'Ready for gameplay',
        body: 'Socket points, collision primitives and a simple Blueprint-compatible animation rig are included in the deliverable. Ready to be imported and attached to a character skeleton on arrival.'
      },
      inline: {
        title: 'Refraction',
        body: 'Index of refraction tuned to 1.52 for lead crystal. Dispersion faked with a three-channel UV offset in post.'
      },
      motionBlocks: null
    }
  },
  'recon-drone': {
    role: 'Personal',
    tools: [
      'Blender',
      'Substance Painter',
      'UE5'
    ],
    modelSrc: './assets/models/recon-drone.glb',
    modelStats: {
      triangles: '496',
      vertices: '266',
      materials: 3,
      textures: 'Procedural (PBR)',
      software: 'Blender'
    },
    items: {
      media: [
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/recon-drone/01.svg',
          bg: 'linear-gradient(135deg,#1c2030 0%,#28303e 100%)',
          label: 'Completed model',
          desc: 'Tactical UAV prop. Game-ready tri count with full LOD0–LOD2 chain for UE5.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/recon-drone/02.svg',
          bg: 'linear-gradient(135deg,#181c2a 0%,#242c38 100%)',
          label: 'Exploded view',
          desc: 'Separated components rendered with distance-based transparency. Used in pitch deck.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/recon-drone/03.svg',
          bg: 'linear-gradient(135deg,#141828 0%,#202834 100%)',
          label: 'LOD comparison',
          desc: 'Side-by-side LOD0 (14 k), LOD1 (5.6 k) and LOD2 (1.8 k) with silhouette preservation.',
          enabled: true
        },
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/recon-drone/04.svg',
          bg: 'linear-gradient(135deg,#101424 0%,#1c2430 100%)',
          label: 'Rotor animation',
          desc: 'Dual-blade rotor cycle baked into mesh. 120 fps loop for seamless idle state.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/recon-drone/05.svg',
          bg: 'linear-gradient(135deg,#0c1020 0%,#181e2c 100%)',
          label: 'Decal library',
          desc: 'Set of 12 modular decals (serials, hazard tape, unit IDs) for squad personalisation.',
          enabled: true
        }
      ],
      text: {
        title: 'Engine-side integration',
        body: 'The drone ships with an Unreal-ready Blueprint actor, socket points for the antenna and gimbal, and a material parameter collection for easy colourway swaps without duplicating assets.'
      },
      inline: {
        title: 'Modularity',
        body: 'Payload bay accepts 6 swappable modules. Each snaps via a shared 3-pin connector — no per-module rigging required.'
      },
      motionBlocks: null
    }
  },
  'apex-frame': {
    role: 'Client',
    tools: [
      'Blender',
      'CAD export',
      'Inkscape'
    ],
    modelSrc: './assets/models/apex-frame.glb',
    modelStats: {
      triangles: '12,200',
      vertices: '6,300',
      materials: 4,
      textures: '4 × 2 K',
      software: 'ZBrush + Blender'
    },
    items: {
      media: [
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/apex-frame/01.svg',
          bg: 'linear-gradient(135deg,#202428 0%,#2c3034 100%)',
          label: 'Assembly render',
          desc: 'Mechanical component breakdown for engineering client. Manufacturing-reference accuracy.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/apex-frame/02.svg',
          bg: 'linear-gradient(135deg,#1c2024 0%,#282c30 100%)',
          label: 'Component detail',
          desc: 'Tolerance callouts overlaid on photorealistic render for internal design review.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/apex-frame/03.svg',
          bg: 'linear-gradient(135deg,#181c20 0%,#24282c 100%)',
          label: 'Engineering ref',
          desc: 'Annotated PDF and STEP export handed off directly to manufacturing partner.',
          enabled: true
        },
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/apex-frame/04.svg',
          bg: 'linear-gradient(135deg,#14181c 0%,#202428 100%)',
          label: 'Stress overlay',
          desc: 'FEA colour map composited onto mesh render for pitch deck to investors.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/apex-frame/05.svg',
          bg: 'linear-gradient(135deg,#101418 0%,#1c2024 100%)',
          label: 'Prototype photo',
          desc: 'Side-by-side of render and machined prototype. Geometry lines up within tolerance.',
          enabled: true
        }
      ],
      text: {
        title: 'Engineering-grade',
        body: 'Files were exported at full 1:1 scale with real-world units baked in. All holes, threads and fillets match the STEP source that went to the CNC shop — nothing is "eyeballed".'
      },
      inline: {
        title: 'Impact geo',
        body: 'Deformable plate zones pre-sculpted in 5 stages. Blend shapes drive runtime damage without additional draw calls.'
      },
      motionBlocks: null
    }
  },
  'core-rig': {
    role: 'R&D',
    tools: [
      'Blender',
      'Meshmixer',
      'Cura'
    ],
    modelSrc: './assets/models/core-rig.glb',
    modelStats: {
      triangles: '464',
      vertices: '240',
      materials: 2,
      textures: 'Procedural (PBR)',
      software: 'Blender + Fusion 360'
    },
    items: {
      media: [
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/core-rig/01.svg',
          bg: 'linear-gradient(135deg,#1e2830 0%,#28363e 100%)',
          label: 'Structural view',
          desc: 'Structural assembly prototype modeled for 3D-print validation and form-factor approval.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/core-rig/02.svg',
          bg: 'linear-gradient(135deg,#1a2428 0%,#24303a 100%)',
          label: 'Section cut',
          desc: 'Cross-section render exposing interior wall thickness for print clearance verification.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/core-rig/03.svg',
          bg: 'linear-gradient(135deg,#161e24 0%,#202c34 100%)',
          label: 'Print validation',
          desc: 'Final mesh passed through Meshmixer slicer. Zero errors, overhang angle within tolerance.',
          enabled: true
        },
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/core-rig/04.svg',
          bg: 'linear-gradient(135deg,#121a20 0%,#1c2830 100%)',
          label: 'Support map',
          desc: 'Predicted support regions overlaid in blue. Used to iterate the orientation before slicing.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/core-rig/05.svg',
          bg: 'linear-gradient(135deg,#0e161c 0%,#18242c 100%)',
          label: 'Fit test render',
          desc: 'Assembly of the printed prototype with its mating housing. Photogrammetry alignment check.',
          enabled: true
        }
      ],
      text: {
        title: 'Print-first design',
        body: 'The geometry is modelled around FDM constraints — 45° overhang rules, wall-thickness minimums and bridging limits — so the file can go straight to a slicer without manual repair.'
      },
      inline: {
        title: 'Joint library',
        body: 'Custom IK handle with stretch-and-squash limits. Retargets to Mixamo and Mannequin out of the box.'
      },
      motionBlocks: null
    }
  },
  'helix-reveal': {
    role: 'R&D',
    tools: [
      'Blender',
      'DaVinci Resolve'
    ],
    modelSrc: './assets/models/helix-reveal.glb',
    modelStats: {
      triangles: '168',
      vertices: '112',
      materials: 1,
      textures: 'Procedural (PBR)',
      software: 'Blender'
    },
    items: {
      media: [
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/helix-reveal/01.svg',
          bg: 'linear-gradient(135deg,#1a2233 0%,#26304a 100%)',
          label: 'Final frame',
          desc: 'Product reveal animation — 6-second loop rendered for a hero section background.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/helix-reveal/02.svg',
          bg: 'linear-gradient(135deg,#161e2e 0%,#222c44 100%)',
          label: 'Storyboard',
          desc: 'Hand-drawn beat sheet translated to Blender timeline. 6 key poses over 180 frames.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/helix-reveal/03.svg',
          bg: 'linear-gradient(135deg,#121a28 0%,#1e283e 100%)',
          label: 'Render settings',
          desc: '4K @ 60 fps, Cycles path-trace, 512 samples. Denoised in OptiX. Exported as ProRes 4444.',
          enabled: true
        },
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/helix-reveal/04.svg',
          bg: 'linear-gradient(135deg,#0e1624 0%,#182238 100%)',
          label: 'Camera moves',
          desc: 'Two-layer parallax camera setup — dolly track plus subtle handheld noise for energy.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/helix-reveal/05.svg',
          bg: 'linear-gradient(135deg,#0a1220 0%,#141e30 100%)',
          label: 'Colour grade',
          desc: 'Teal-orange grade applied in DaVinci Resolve. Matches the brand launch trailer palette.',
          enabled: true
        }
      ],
      text: {
        title: 'Built for loops',
        body: 'Every motion curve is shaped so the last frame matches the first. The 6-second cycle can play forever as a hero background without a visible cut.'
      },
      inline: {
        title: 'Animation',
        body: '12-second loop at 24 FPS. DNA helix unwinds via a single angle-driven shader — no armature, no bake.'
      },
      motionBlocks: null
    }
  },
  'arc-motion': {
    role: 'R&D',
    tools: [
      'Blender',
      'DaVinci Resolve',
      'Nuke'
    ],
    modelSrc: './assets/models/arc-motion.glb',
    modelStats: {
      triangles: '1,856',
      vertices: '930',
      materials: 2,
      textures: 'Procedural (PBR)',
      software: 'Blender'
    },
    items: {
      media: [
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/arc-motion/01.svg',
          bg: 'linear-gradient(135deg,#1f1a2a 0%,#2a2438 100%)',
          label: 'Orbit frame',
          desc: 'Turntable sequence for industrial product — 360° orbit, 4K export with motion blur.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/arc-motion/02.svg',
          bg: 'linear-gradient(135deg,#1b1626 0%,#262034 100%)',
          label: 'Lighting pass',
          desc: '3-layer HDRI rig with gel-coloured area lights. Lighting designed to match brand guidelines.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/arc-motion/03.svg',
          bg: 'linear-gradient(135deg,#171222 0%,#221e30 100%)',
          label: 'Export settings',
          desc: 'Delivered as 4K MP4 (H.264), WebM (VP9), and individual PNG sequence for compositing.',
          enabled: true
        },
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/arc-motion/04.svg',
          bg: 'linear-gradient(135deg,#130e1e 0%,#1e1a2c 100%)',
          label: 'Motion blur',
          desc: 'Per-object velocity pass rendered separately so the client can tune blur amount in post.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/arc-motion/05.svg',
          bg: 'linear-gradient(135deg,#0f0a1a 0%,#181428 100%)',
          label: 'Compositing AOVs',
          desc: 'Cryptomatte, depth, ID and position passes delivered for flexible relight in Nuke.',
          enabled: true
        }
      ],
      text: {
        title: 'Delivery formats',
        body: 'Shipped as a master ProRes file plus H.264, WebM and an image sequence. Same timing, three containers — ready for web, print and post-production pipelines.'
      },
      inline: {
        title: 'Motion curves',
        body: 'Custom ease-out-expo for the main arc. Secondary trails use bezier splines sampled at 60 FPS.'
      },
      motionBlocks: null
    }
  },
  'nyx-panther': {
    role: 'Personal',
    tools: [
      'ZBrush',
      'Blender',
      'XGen'
    ],
    modelSrc: './assets/models/nyx-panther.glb',
    modelStats: {
      triangles: '1,352',
      vertices: '690',
      materials: 1,
      textures: '1 × 2 K',
      software: 'ZBrush + Blender'
    },
    items: {
      media: [
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/nyx-panther/01.svg',
          bg: 'linear-gradient(135deg,#1a1816 0%,#2a2520 100%)',
          label: 'Full body pose',
          desc: 'Stylized feline creature. Hand-sculpted anatomy, two-coat fur groom, stylised musculature.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/nyx-panther/02.svg',
          bg: 'linear-gradient(135deg,#161411 0%,#241f1a 100%)',
          label: 'Fur pass',
          desc: 'Dual-layer fur groom — undercoat + guard hairs with procedural clumping and asymmetry.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/nyx-panther/03.svg',
          bg: 'linear-gradient(135deg,#12100e 0%,#1e1a16 100%)',
          label: 'Head study',
          desc: 'Facial sculpt focused on eye rhythm and nasal break. Fine whisker cards placed manually.',
          enabled: true
        },
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/nyx-panther/04.svg',
          bg: 'linear-gradient(135deg,#0e0c0a 0%,#181614 100%)',
          label: 'Silhouette cards',
          desc: 'Action pose library with 6 silhouettes used to lock animation feel before keyframing.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/nyx-panther/05.svg',
          bg: 'linear-gradient(135deg,#0a0908 0%,#141210 100%)',
          label: 'Prowl animation',
          desc: 'Looped prowl cycle at 30 fps. Cloth-free skeleton mesh for real-time preview in viewport.',
          enabled: true
        }
      ],
      text: {
        title: 'Character intent',
        body: 'Designed as a neutral hero creature for a stealth-focused narrative. Silhouette reads in both light and dark environments, and the fur groom simplifies cleanly to real-time cards.'
      },
      inline: {
        title: 'Fur grooming',
        body: 'Dual-coat setup: guide hairs hand-sculpted, undercoat scattered via density map. Groom exports to Alembic at 1.2 M splines.'
      },
      motionBlocks: null
    }
  },
  'drift-koi': {
    role: 'Personal',
    tools: [
      'ZBrush',
      'Blender',
      'Substance Painter'
    ],
    modelSrc: './assets/models/drift-koi.glb',
    modelStats: {
      triangles: '168',
      vertices: '112',
      materials: 1,
      textures: 'Procedural (PBR)',
      software: 'ZBrush + Blender'
    },
    items: {
      media: [
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/drift-koi/01.svg',
          bg: 'linear-gradient(135deg,#161e24 0%,#1f2a34 100%)',
          label: 'Hero render',
          desc: 'Ornamental fish study. Displacement scales, three-layer subsurface scattering pass.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/drift-koi/02.svg',
          bg: 'linear-gradient(135deg,#121a20 0%,#1a2630 100%)',
          label: 'Scale macro',
          desc: 'Procedural scale pattern sculpted in ZBrush and driven by a curve-based UV layout.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/drift-koi/03.svg',
          bg: 'linear-gradient(135deg,#0e161c 0%,#18222c 100%)',
          label: 'Fin study',
          desc: 'Thin-film interference on the tail fin. Double-sided shader with anisotropic highlights.',
          enabled: true
        },
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/drift-koi/04.svg',
          bg: 'linear-gradient(135deg,#0b1218 0%,#141e28 100%)',
          label: 'Swim loop',
          desc: 'Seamless 3-second swim cycle driven by a spline rig. Ready for particle systems and aquariums.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/drift-koi/05.svg',
          bg: 'linear-gradient(135deg,#080f14 0%,#101a24 100%)',
          label: 'Variant pattern',
          desc: 'Seven patterning variants — Kohaku, Showa, Asagi and custom — via mask blending.',
          enabled: true
        }
      ],
      text: {
        title: 'Organic shading',
        body: 'The scale shader reads as wet without looking plastic. A combination of displacement, anisotropic highlight and soft subsurface response keeps the surface grounded even under harsh lighting.'
      },
      inline: {
        title: 'Scale shader',
        body: 'Iridescent scales driven by fresnel × vertex color. Three variants — koi red, shusui blue, asagi silver — toggle via material ID.'
      },
      motionBlocks: null
    }
  },
  'glint-owl': {
    role: 'Personal',
    tools: [
      'ZBrush',
      'Blender',
      'Houdini groom'
    ],
    modelSrc: './assets/models/glint-owl.glb',
    modelStats: {
      triangles: '496',
      vertices: '266',
      materials: 3,
      textures: 'Procedural (PBR)',
      software: 'ZBrush + Blender'
    },
    items: {
      media: [
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/glint-owl/01.svg',
          bg: 'linear-gradient(135deg,#1a1a22 0%,#262632 100%)',
          label: 'Portrait render',
          desc: 'Stylized bird character. Feather grooming with procedural asymmetry and wind drift.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/glint-owl/02.svg',
          bg: 'linear-gradient(135deg,#16161e 0%,#20202c 100%)',
          label: 'Wing spread',
          desc: 'Fully posed flight wing with hand-placed primaries and secondaries on a bone chain.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/glint-owl/03.svg',
          bg: 'linear-gradient(135deg,#12121a 0%,#1a1a26 100%)',
          label: 'Feather cards',
          desc: 'Texture sheet of 40 individual feather cards used by the groom and LOD feather planes.',
          enabled: true
        },
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/glint-owl/04.svg',
          bg: 'linear-gradient(135deg,#0e0e16 0%,#161620 100%)',
          label: 'Beak & talon',
          desc: 'Hero keratin shader — glossy micro-surface, warm subsurface — applied to beak and talons.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/glint-owl/05.svg',
          bg: 'linear-gradient(135deg,#0a0a12 0%,#12121c 100%)',
          label: 'Silhouette lineup',
          desc: 'Eight pose silhouettes used to lock mood before the final groom pass was started.',
          enabled: true
        }
      ],
      text: {
        title: 'Groom system',
        body: 'The entire plumage is driven by one groom modifier with density, length and clumping masks. Editing the mask updates every feather at once — no hand-placing individual strands.'
      },
      inline: {
        title: 'Feather layers',
        body: 'Body feathers groomed per zone: head, chest, primaries. Alpha-cards for silhouette, shell geometry for flight feathers.'
      },
      motionBlocks: null
    }
  },
  'mech-link': {
    role: 'R&D',
    tools: [
      'Fusion 360',
      'Blender',
      'KeyShot'
    ],
    modelSrc: './assets/models/mech-link.glb',
    modelStats: {
      triangles: '512',
      vertices: '264',
      materials: 2,
      textures: 'Procedural (PBR)',
      software: 'Fusion 360 + Blender'
    },
    items: {
      media: [
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/mech-link/01.svg',
          bg: 'linear-gradient(135deg,#1d232a 0%,#2a3138 100%)',
          label: 'Assembly overview',
          desc: 'Industrial link chain assembly. Parametric pin-joint system sourced from CAD.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/mech-link/02.svg',
          bg: 'linear-gradient(135deg,#1a2027 0%,#262d34 100%)',
          label: 'Bracket detail',
          desc: 'Bolt-pattern close-up. Retopology pass prepared for manufacturing review.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/mech-link/03.svg',
          bg: 'linear-gradient(135deg,#171d24 0%,#222930 100%)',
          label: 'Motion study',
          desc: 'Range-of-motion sketch for the pivoting arm. Constraint solver preview.',
          enabled: true
        },
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/mech-link/04.svg',
          bg: 'linear-gradient(135deg,#141a21 0%,#1e252c 100%)',
          label: 'Exploded view',
          desc: 'Parts diagram for manufacture planning. Tolerances marked in source DWG.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/mech-link/05.svg',
          bg: 'linear-gradient(135deg,#11171e 0%,#1a2128 100%)',
          label: 'Material preview',
          desc: 'KeyShot pass — brushed steel and anodized aluminium swatches.',
          enabled: true
        }
      ],
      text: {
        title: 'CAD production study',
        body: 'Parametric link-chain case focused on CAD handoff, tolerance review, and render-ready topology for the CAD category.'
      },
      inline: {
        title: 'Pipeline',
        body: 'Fusion 360 → STEP → Blender retopo → KeyShot marketing. The assembly is ready for CAD review and render handoff.'
      },
      motionBlocks: null
    }
  },
  'flex-spine': {
    role: 'R&D',
    tools: [
      'Fusion 360',
      'Blender',
      'KeyShot'
    ],
    modelSrc: './assets/models/flex-spine.glb',
    modelStats: {
      triangles: '496',
      vertices: '258',
      materials: 2,
      textures: 'Procedural (PBR)',
      software: 'Fusion 360 + Blender'
    },
    items: {
      media: [
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/flex-spine/01.svg',
          bg: 'linear-gradient(135deg,#21272d 0%,#2e353c 100%)',
          label: 'Spine assembly',
          desc: 'Kinematic spine assembly. Parametric ribs driven by a single driver angle.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/flex-spine/02.svg',
          bg: 'linear-gradient(135deg,#1d232a 0%,#2a3138 100%)',
          label: 'Rib section',
          desc: 'Section-cut through one rib — thickness and fillet radii exposed as parameters.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/flex-spine/03.svg',
          bg: 'linear-gradient(135deg,#1a2027 0%,#262c33 100%)',
          label: 'Deflection test',
          desc: 'FEA sketch — deflection map under 50 N lateral load, prepared for design review.',
          enabled: true
        },
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/flex-spine/04.svg',
          bg: 'linear-gradient(135deg,#171d24 0%,#222930 100%)',
          label: 'Joint detail',
          desc: 'Ball-and-socket joint close-up. Tolerance stack-up listed in source PDF.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/flex-spine/05.svg',
          bg: 'linear-gradient(135deg,#141a21 0%,#1e252c 100%)',
          label: 'Render study',
          desc: 'KeyShot pass — matte steel against cool grey backdrop.',
          enabled: true
        }
      ],
      text: {
        title: 'Kinematic CAD study',
        body: 'Parametric spine case: one driver angle bends every rib, with render studies prepared for stand and motion review.'
      },
      inline: {
        title: 'Parametrics',
        body: 'Parameters: rib_count, rib_thickness, segment_angle. Linked through Fusion 360 sketches and exported to Blender.'
      },
      motionBlocks: null
    }
  },
  'cad-strut': {
    role: 'R&D',
    tools: [
      'Fusion 360',
      'Blender',
      'KeyShot'
    ],
    modelSrc: './assets/models/cad-strut.glb',
    modelStats: {
      triangles: '480',
      vertices: '248',
      materials: 2,
      textures: 'Procedural (PBR)',
      software: 'Fusion 360 + Blender'
    },
    items: {
      media: [
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/cad-strut/01.svg',
          bg: 'linear-gradient(135deg,#1f2429 0%,#2b3138 100%)',
          label: 'Node overview',
          desc: 'Structural strut node. Six-way connector for space-frame assemblies.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/cad-strut/02.svg',
          bg: 'linear-gradient(135deg,#1c2126 0%,#282e35 100%)',
          label: 'Axis diagram',
          desc: 'Load-path diagram — principal axes marked for the structural engineer.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/cad-strut/03.svg',
          bg: 'linear-gradient(135deg,#191e23 0%,#252b32 100%)',
          label: 'Cross-section',
          desc: 'Section through the central hub. Wall thickness and weld-prep highlighted.',
          enabled: true
        },
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/cad-strut/04.svg',
          bg: 'linear-gradient(135deg,#161b20 0%,#21272e 100%)',
          label: 'Mount plate',
          desc: 'Bolt-circle mount plate. Parametric — updates when strut diameter changes.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/cad-strut/05.svg',
          bg: 'linear-gradient(135deg,#13181d 0%,#1e242b 100%)',
          label: 'Surface finish',
          desc: 'KeyShot pass — powder-coated aluminium, matte warm grey.',
          enabled: true
        }
      ],
      text: {
        title: 'Structural CAD node',
        body: 'Structural strut node with linked diameter, wall thickness, and bolt-pattern parameters for production and render review.'
      },
      inline: {
        title: 'Use case',
        body: 'Used in space-frame prototypes. STEP is exported for CNC; Blender retopo supports marketing renders.'
      },
      motionBlocks: null
    }
  }
};
