/* ═══════════════════════════════════════════════════════════════════════
   cards-data.js — AUTO-GENERATED by scripts/generate-content.mjs. Do not
   edit by hand: run `npm run content:generate` after editing the content
   sources in content/cases/*.json (order: content/settings.json cardOrder).

   window.CARDS_DATA — финальная развёрнутая структура кейсов (бывший
   makeItems() из js/main.js портирован в генератор):
     items.media[] — от 1 до 12 самодостаточных блоков из case.media[]:
       type (image | video), format (wide | tall), явный путь src, фон bg,
       EN-подписи label/desc, плюс необязательные poster и id;
     items.text / items.inline — текстовые блоки (или null);
     items.motionBlocks — fixed motion-секции (или null).
   Подключается ПЕРЕД js/main.js (classic script, без defer/async).
═══════════════════════════════════════════════════════════════════════ */
window.CARDS_DATA = {
  'corten-series': {
    role: 'Client: Happfe',
    tools: [
      'Blender',
      'Substance Painter'
    ],
    modelSrc: './assets/models/corten-series-a5f1c0fb.glb',
    layoutMode: 'manual',
    modelStats: {
      triangles: '401,246',
      vertices: '193,604',
      materials: 2,
      textures: 'PBR',
      software: 'Blender, Painter'
    },
    items: {
      media: [
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/corten-series/01-d1b75be2.jpg',
          bg: 'linear-gradient(135deg,#2a2018 0%,#3a2e22 100%)',
          label: '',
          desc: '',
          enabled: true
        },
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/corten-series/05-dc26ecf5.jpg',
          bg: 'linear-gradient(135deg,#1e1410 0%,#2c2018 100%)',
          label: '',
          desc: '',
          enabled: true
        },
        {
          id: 'media-msbv5509',
          type: 'image',
          format: 'tall',
          src: './assets/cases/corten-series/03-d35162b9.jpg',
          bg: 'linear-gradient(135deg,#1e1410 0%,#2c2018 100%)',
          label: '',
          desc: '',
          enabled: true
        },
        {
          id: 'media-msbv5b5y',
          type: 'image',
          format: 'tall',
          src: './assets/cases/corten-series/04-9dfa2fd8.jpg',
          bg: 'linear-gradient(135deg,#1e1410 0%,#2c2018 100%)',
          label: '',
          desc: '',
          enabled: true
        },
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/corten-series/02-5598d4e4.jpg',
          bg: 'linear-gradient(135deg,#241a14 0%,#34281e 100%)',
          label: '',
          desc: '',
          enabled: true
        },
        {
          id: 'media-msbvd19y',
          type: 'image',
          format: 'wide',
          src: './assets/cases/corten-series/06-164177c7.jpg',
          bg: 'linear-gradient(135deg,#1e1410 0%,#2c2018 100%)',
          label: '',
          desc: '',
          enabled: true
        },
        {
          id: 'media-msbj0s97',
          type: 'image',
          format: 'wide',
          src: './assets/cases/corten-series/04-57e7bbf6.jpg',
          bg: 'linear-gradient(135deg,#1e1410 0%,#2c2018 100%)',
          label: '',
          desc: '',
          enabled: true
        }
      ],
      text: {
        title: 'Product visualization development',
        body: 'Only drawings and raw materials were received from the customer. The materials and textures were finalized. The model was optimized for constant product renders. The GLB was prepared for placement on the website. The drawings were adapted for possible product improvements.'
      },
      inline: {
        title: '20 renders and 2 animations',
        body: 'A total of 20 renders were created, all the client’s scenarios were worked through, and a separate animated video for the opening and closing was produced. The project files have been transferred to the requester.'
      },
      motionBlocks: null,
      cta: {
        url: 'https://www.behance.net/gallery/227387887/Dehydrator'
      },
      blueprints: [
        {
          id: 'bp-msc7sivr',
          src: './assets/cases/corten-series/blueprints/01-687c4903.svg',
          label: 'Front view'
        },
        {
          id: 'bp-mskcpu5n',
          src: './assets/cases/corten-series/blueprints/02-7ceb375d.svg',
          label: 'Side view'
        },
        {
          id: 'bp-mskcpz2v',
          src: './assets/cases/corten-series/blueprints/03-1e70f06c.svg',
          label: 'View from above'
        }
      ]
    }
  },
  'lumen-one': {
    role: 'Client',
    tools: [
      'Blender',
      'Inkscape'
    ],
    modelSrc: './assets/models/lumen-one.glb',
    layoutMode: 'manual',
    modelStats: {
      triangles: '1,352',
      vertices: '690',
      materials: 1,
      textures: '1 × 2 K',
      software: 'Blender + Substance'
    },
    items: {
      media: [
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/lumen-one/01.svg',
          bg: 'linear-gradient(135deg,#1e2428 0%,#2c3640 100%)',
          label: 'Final render',
          desc: 'Architectural lighting unit. Photorealistic turntable deliverable for investor pitch deck.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/lumen-one/02.svg',
          bg: 'linear-gradient(135deg,#1a2024 0%,#28303c 100%)',
          label: 'Lighting setup',
          desc: '3-point HDRI rig with area light fill. Caustics rendered via path-tracing at 4096 samples.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/lumen-one/03.svg',
          bg: 'linear-gradient(135deg,#161c20 0%,#222c38 100%)',
          label: 'Spec sheet',
          desc: 'Dimension overlay and material callout sheet generated in Blender Compositing and Inkscape.',
          enabled: true
        },
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/lumen-one/04.svg',
          bg: 'linear-gradient(135deg,#11181c 0%,#1c2832 100%)',
          label: 'Context shot',
          desc: 'Hero placement in a modern office environment, shot from client-approved camera angle.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/lumen-one/05.svg',
          bg: 'linear-gradient(135deg,#0c1418 0%,#18242e 100%)',
          label: 'Colour variants',
          desc: 'Six finish variants — brass, chrome, matte black, warm white — rendered as catalogue sprites.',
          enabled: true
        }
      ],
      text: {
        title: 'Light behaviour',
        body: 'The optical housing uses a real IES profile exported from the client’s photometric test. Caustics and beam spread on camera match what the product produces on a physical wall.'
      },
      inline: {
        title: 'Light model',
        body: 'Filament IES bakes drive the emissive intensity map. Inner diffuser scatters via subsurface approximation — no cheat geometry.'
      },
      motionBlocks: null
    }
  },
  'flux-capsule': {
    role: 'R&D',
    tools: [
      'Blender',
      'Substance Painter'
    ],
    modelSrc: './assets/models/flux-capsule.glb',
    modelStats: {
      triangles: '608',
      vertices: '312',
      materials: 3,
      textures: 'Procedural (PBR)',
      software: 'Blender'
    },
    items: {
      media: [
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/flux-capsule/01.svg',
          bg: 'linear-gradient(135deg,#1e2030 0%,#282a40 100%)',
          label: 'Product shot',
          desc: 'Consumer tech device. E-commerce hero shot with studio HDRI and custom denoising.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/flux-capsule/02.svg',
          bg: 'linear-gradient(135deg,#1a1c2c 0%,#24263c 100%)',
          label: '360° view',
          desc: 'Full turntable sequence — 36 frames at 10° increments. Exported as WebP sprite strip.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/flux-capsule/03.svg',
          bg: 'linear-gradient(135deg,#161828 0%,#202234 100%)',
          label: 'Detail macro',
          desc: 'Micro-surface texture pass. Sub-millimetre detail captured with a virtual macro lens rig.',
          enabled: true
        },
        {
          type: 'image',
          format: 'wide',
          src: './assets/cases/flux-capsule/04.svg',
          bg: 'linear-gradient(135deg,#12142a 0%,#1c1e30 100%)',
          label: 'Packaging',
          desc: 'Retail box render with reflective foil stamping, printed using PBR metallic-clearcoat.',
          enabled: true
        },
        {
          type: 'image',
          format: 'tall',
          src: './assets/cases/flux-capsule/05.svg',
          bg: 'linear-gradient(135deg,#0e102a 0%,#181a2a 100%)',
          label: 'Scale ref',
          desc: 'Hand comparison render to communicate size without breaking photo-neutral background.',
          enabled: true
        }
      ],
      text: {
        title: 'Launch ready',
        body: 'All hero assets were delivered as 6 K master renders plus derivative crops for Shopify, Amazon and paid-social ad placements. Colour profile matches the brand Pantone book.'
      },
      inline: {
        title: 'Containment',
        body: 'Animated shader on the core reads a custom gradient texture — no vertex morph, no simulation cache. Runs at 240 FPS on mid-range GPUs.'
      },
      motionBlocks: null
    }
  }
};
