export default {
  extends: ['stylelint-config-standard'],
  ignoreFiles: [
    'node_modules/**',
    'js/vendor/**',
    'assets/**',
    'downloads/**',
    'playwright-report/**',
    'test-results/**'
  ],
  rules: {
    'alpha-value-notation': null,
    'at-rule-empty-line-before': null,
    'color-function-notation': null,
    'color-function-alias-notation': null,
    'color-hex-length': null,
    'comment-empty-line-before': null,
    'custom-property-empty-line-before': null,
    'custom-property-pattern': null,
    'declaration-block-single-line-max-declarations': null,
    'declaration-block-no-redundant-longhand-properties': null,
    'declaration-empty-line-before': null,
    'font-family-no-missing-generic-family-keyword': null,
    'function-calc-no-unspaced-operator': null,
    'hue-degree-notation': null,
    'keyframes-name-pattern': null,
    'lightness-notation': null,
    'media-feature-range-notation': null,
    'no-descending-specificity': null,
    'no-duplicate-selectors': null,
    'property-no-deprecated': null,
    'property-no-vendor-prefix': null,
    'rule-empty-line-before': null,
    'selector-class-pattern': null,
    'selector-id-pattern': null,
    'selector-not-notation': null,
    'shorthand-property-no-redundant-values': null,
    'value-keyword-case': null,
    'value-no-vendor-prefix': null
  }
};
