/* ═════════════════════════════════════════════════════════════════════════════
   i18n-data.js — AUTO-GENERATED by scripts/generate-content.mjs. Do not edit
   by hand: run `npm run content:generate` after editing the content sources.

   Sources:
     - content/i18n-ui.json        → UI_STRINGS (en+ru fully expanded)
     - content/meta.json           → META_STRINGS (en+ru)
     - content/cases/*.json        → CARDS_LOCALES + CASE_LOCALES (en+ru)
     - content/free-assets.json    → FA_LOCALES (en+ru)

   Словари для переключателя RU/EN. Технические термины и англицизмы
   (Hard Surface, Product Viz, CAD, PBR, LOD и т.п.) остаются одинаковыми
   в EN и RU — принцип "никогда не переводить" сохранён в данных.

   Persistence: URL ?lang=ru|en. NO localStorage / sessionStorage / cookies.
   ═════════════════════════════════════════════════════════════════════════════ */
(function () {
  'use strict';

  const CIS_COUNTRIES = ['RU', 'BY', 'KZ', 'KG', 'UZ', 'TJ', 'AM', 'AZ', 'MD'];

  // ── UI_STRINGS — dot-notation ключи, парсятся window.I18N.t('aria.contactTelegram') ──
  const UI_STRINGS = __UI_STRINGS__;

  // ── META_STRINGS — per-page meta (index / fa), data-i18n-meta="index.title" и т.п. ──
  const META_STRINGS = __META_STRINGS__;

  // ── CARDS_LOCALES — work-card title/desc/alt по data-id (18 кейсов) ──
  const CARDS_LOCALES = __CARDS_LOCALES__;

  // ── CASE_LOCALES — case-view контент (role / captions / text / inline / motionBlocks) ──
  const CASE_LOCALES = __CASE_LOCALES__;

  // ── FA_LOCALES — free-assets каталог, переводится только desc ──
  const FA_LOCALES = __FA_LOCALES__;

  window.I18N_DATA = {
    CIS_COUNTRIES: CIS_COUNTRIES.slice(),
    UI_STRINGS: UI_STRINGS,
    META_STRINGS: META_STRINGS,
    CARDS_LOCALES: CARDS_LOCALES,
    CASE_LOCALES: CASE_LOCALES,
    FA_LOCALES: FA_LOCALES,
  };
})();
